実践 Lottie
pjhjohn/DroidKaigi2019-KR pull request #2
Opened 2018-12-12 20:05 UTC by maryangmin

2018-12-13 04:16 UTC, Pluu reviewed
@maryangmin 확인했습니다. 👍

2018-12-13 04:16 UTC, Pluu commented on ACCEPTED_SESSIONS_KR.md
> +제가 담당하고 있는 프로덕트에서 Lottie를 사용해 개발을 하였습니다.
`Lottie를` 이라고 `을/를`을 한번 언급했기에, 뒤쪽의 `을/를`은 생략되는편이 더 읽기 매끄러울듯해요 
개발을 하였습니다. --> `개발하였습니다`

2018-12-13 04:16 UTC, Pluu commented on ACCEPTED_SESSIONS_KR.md
> +그 결과 Android / iOS에서 부드럽게 리치한 애니메이션을 사용하여 구현할 수 있었습니다.
한국에서도 `리치`라고 표현하는지 다른분에게 턴을 넘겨봅니다.

2018-12-13 10:40 UTC, pjhjohn requested changes
아래와 같이 `README.md` 의 해당 항목에도 `x`표를 쳐 주십시옹!
그럼 이렇게 보임 ㅎㅎ
- [x] ~~実践 Lottie~~
```
- [x] ~~実践 Lottie~~
```

FYI, 이 **Request Change** 는 번역의 수정 요청이 아니라, 위의 내용에 의한 것입니당!

2018-12-13 10:40 UTC, pjhjohn commented on ACCEPTED_SESSIONS_KR.md
> +제가 담당하고 있는 프로덕트에서 Lottie를 사용해 개발을 하였습니다.
문장이 조금 더 간결하게 정리되면 번역체의 느낌이 더 적게 날 것 같당!
`담당하고 있는` => `담당하는`
`개발을 하였습니다` => `개발했습니다`

2018-12-13 10:40 UTC, pjhjohn commented on ACCEPTED_SESSIONS_KR.md
> +그 결과 Android / iOS에서 부드럽게 리치한 애니메이션을 사용하여 구현할 수 있었습니다.
한국에서도 딱히 `리치` 라는 단어를 폭넓게 사용하진 않는 것 같아요.
**스무스하게 풍부한 애니메이션을 사용해** 정도의 느낌이 좋을 것 같은데, **스무스**가 뒤의 문장 전체를 꾸며주는 역할인 것 같아서 `부드럽게` 로 번역하는게 맞을지 잘 모르겠네... 
**부드럽고 풍부한 애니메이션** 이 되려면 と가 붙어야하지 않을라나.... 🤔

2018-12-13 10:40 UTC, pjhjohn commented on ACCEPTED_SESSIONS_KR.md
> +엔지니어의 힘을 빌리지 않고 리치 애니메이션을 도입하고 싶은 분
`리치`라는 단어를 사용하더라도, な가 있기 때문에 `리치한` 이 더 적합하지 않을까??

2018-12-13 13:41 UTC, maryangmin commented on ACCEPTED_SESSIONS_KR.md
> +제가 담당하고 있는 프로덕트에서 Lottie를 사용해 개발을 하였습니다.
`담당하고 있는` => `담당하는` 수정 완료
`개발을 하였습니다` => `개발하였습니다` 수정 완료
`개발했습니다` 는 구어체 느낌이 나서 @Pluu 님 안을 채택

2018-12-13 13:44 UTC, maryangmin commented on ACCEPTED_SESSIONS_KR.md
> +그 결과 Android / iOS에서 부드럽게 리치한 애니메이션을 사용하여 구현할 수 있었습니다.
`리치 애니메이션` 이라는 표현이 존재는 합니다만 `풍부한 애니메이션`이 의미가 더 잘 와닿을 것 같네요. 수정하겠습니다.

2018-12-13 13:44 UTC, maryangmin commented on ACCEPTED_SESSIONS_KR.md
> +엔지니어의 힘을 빌리지 않고 리치 애니메이션을 도입하고 싶은 분
`풍부한`으로 변경

2018-12-13 16:13 UTC, Pluu approved these changes

2018-12-13 16:13 UTC, Pluu commented
@pjhjohn Reviewお願いします。🙏

2018-12-13 18:03 UTC, maryangmin commented
취소선까지 추가하였음. Merge Block는 준호가 approve하면 풀리는건가?

2018-12-13 23:57 UTC, pjhjohn approved these changes

2018-12-14 00:56 UTC, pjhjohn commented
@maryangmin 얍얍 승인 2개하면 풀리게 되어있습니당!

2018-12-14 00:57 UTC, merged